#!/usr/bin/env bash

# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2025 Onestein B.V.

set -eo pipefail

mode="${DNS01_MODE:-idle}"

case "$mode" in
  idle)
    echo "[entrypoint] starting idle mode"
    tail -f /dev/null
    ;;

  spool)
    echo "[entrypoint] starting spool mode"

    [[ -z "$DNS01_SPOOL" ]] && DNS01_SPOOL="${SPOOL_DIR:-$DNS01_PATH}"

    if [[ -n "$SPOOL_DIR" ]] && [[ ! -d "$SPOOL_DIR" ]]; then mkdir "$SPOOL_DIR"
    elif [[ ! -d "$DNS01_SPOOL/spool" ]]; then mkdir "$DNS01_SPOOL/spool"
    fi

    [[ "$DNS01_SPOOL" != "$DNS01_PATH" ]] && cp -f "$DNS01_PATH/spool.sh" "$DNS01_SPOOL"

    SPOOL_JOB=dns01 exec "$DNS01_SPOOL/spool.sh" daemon
    ;;

  certbot)
    echo "[entrypoint] starting certbot mode"
    exec "$DNS01_PATH/dns01" "$@"
    ;;

  certbot-long)
    echo "[entrypoint] Long-lived certbot mode is not yet implemented"
    exit 2
    ;;

  listen)
    echo "[entrypoint] Listen mode is not yet implemented"
    exit 2
    ;;

  *)
    echo "[entrypoint] Unknown mode '$mode'. Supported: idle, spool, certbot, certbot-long, listen"
    exit 1
    ;;
esac
