#!/usr/bin/env bash

# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2025 Onestein B.V.

set -o pipefail

declare -A script conf err hint

err[ok]=0
err[fail]=1
err[network]=10
err[parse]=20
err[auth]=30
err[api]=40

hint[http50]='Slow down or wait a minute'
hint[http80]='Check required fields / JSON shape'
hint[http81]='Wrong HTTP verb / endpoint'
hint[http98]='Check that object belongs to your account'
hint[http99]='Nothing matched the filter'

# boilerplate helper
# regex match prefixed env vars to conf[] entries
env2conf(){
  local v prefix="$1" rx="$2"
  shift 2

  for v in "$@"; do
    v="${prefix}${v^^}"
    [[ "${!v}" =~ $rx ]] && conf[${v,,}]="${!v}"
  done
}

msg() { printf '%s %s[%s] %s\n' "$(date '+%Y-%m-%dT%TZ')" "${JOB_ID:+job $JOB_ID }" "${script[name]}" "$*" >&2; }

err() {
  local code="${1:-1}" msg hint_msg

  [[ -v "hint[$code]" ]] && hint_msg="${hint[$code]}"

  if [[ -v "err[$code]" ]]; then shift
  else
    [[ -v "hint[$code]" ]] && shift
    code=fail
  fi

  case "$code" in
      ok) msg="OK"            ;;
    fail) msg="error"         ;;
       *) msg="error($code)"  ;;
  esac

  if (( $# )); then msg+=": $*${hint_msg:+ - $hint_msg}"
  else msg+="${hint_msg:+: $hint_msg}"
  fi

  msg "$msg"

  exit "${err[$code]}"
}
